### ISSUE TITLE
Feature : Create User Schema Model

### ISSUE THREAD

**Issue by fallen-ecstasy** [fallen-ecstasy/NovaCode-Server#1]
### User Schema

```js
User:{
    _id: ObjectId,
    name: string,
    sessionCount: number,
    email: string,
    pass: string,
    dob: Date,
    solved: [ObjectId],
    attempted: [ObjectId],
}
```

- Create this User Model in the `./src/Models/` Folder, If the folder is not present create it yourself.
- Create an Interface for the Schema to ensure type-checking.

---

### Testing

- Write a Test in Mocha + Chai to test Database Entries.

**Comment by iamrishiksahu** [comment]
I am interested to work on this issue, Kindly assign it to me so that I can start asap.

**Comment by fallen-ecstasy** [comment]
@iamrishiksahu There is a Update in Package.json
update your local repo with `git pull`

**Comment by iamrishiksahu** [comment]
Okay, I'll make sure there are no merge conflicts.
