### ISSUE TITLE
Feature : Create a User Profile APIs

### ISSUE THREAD

**Issue by fallen-ecstasy** [fallen-ecstasy/NovaCode-Server#4]
### Endpoint 1: Get Public User Profile

- Path: `/user/profile/:username` (PUBLIC)
- HTTP Method: `GET`

#### Request Template:
```js
// No request required for public profile
```
##### Response Template:
```js
{
  "id": "string",
  "username": "string",
  "email": "string",
  // Complete user Details except Pass and Email...
}
```
#### Guidelines for Contributor:
- Ensure that this endpoint provides only public information about the user.
- Include essential details like ID, username, and other details in the response.
- Consider adding more information based on the project's requirements.

---

### Endpoint 2: Get the Current User Profile

- Path: `/user/myprofile`
- HTTP Method: `GET`

#### Request Template:
```js
// No request required for fetching own profile
```

#### Response Template:
```js
{
  "id": "string",
  "username": "string",
  "email": "string",
  // Complete user Details except Pass ...
}
```

#### Guidelines for Contributor:
- This endpoint should provide detailed information about the currently logged-in user.
- Include ID, username, email, and any additional details stored in the user's profile.

 ---

### Endpoint 3: Edit User Profile

- Path: `/user/editprofile`
- HTTP Method: `PATCH`
#### Request Template:
```js
{
  "email": "string",
  // Additional fields for modification...
}
```

#### Response Template:
```js
{
  "id": "string",
  "username": "string",
  "email": "string",
  // Additional updated profile details...
}
```
#### Guidelines for Contributor:
- Allow users to update their profiles by sending a PATCH request with the desired modifications.
- Validate and update the provided fields accordingly.
- Enhance Existing Model and Register API:

### Model Enhancement:

- Add a "username" field to the user model.

### Register API Enhancement:
- Modify the Register API to include a "username" field in the request.
- Check whether the provided username is unique. If not, return an appropriate error message.

---

### Optional: Write Test

- Write Tests in Mocha + Chai to test the User API.
- Write Tests in Mocha + Chai to test new Model Enhancement.

**Comment by ghostbadfame** [comment]
Hey, I want to solve this issue.

**Comment by rahul9852-dot** [comment]
@fallen-ecstasy I'm working on it.

**Comment by fallen-ecstasy** [comment]
@rahul9852-dot Any update on the Issue ?

**Comment by rahul9852-dot** [comment]
Working on it. wait till tomorrow
